# Generated by Django 3.2.12 on 2022-03-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa waloru')),
                ('code', models.CharField(max_length=20, verbose_name='Kod waloru')),
                ('price', models.FloatField(verbose_name='Kurs')),
                ('date', models.DateTimeField(verbose_name='data i czas pobrania')),
            ],
        ),
    ]
