# Generated by Django 3.2.12 on 2022-03-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'Stats'},
        ),
    ]
