# Generated by Django 3.2.12 on 2022-03-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_stats_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.CharField(max_length=20, verbose_name='data i czas pobrania'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Kurs'),
        ),
    ]
